name: Add Missing Project Directories

on:
  workflow_dispatch: # Дозволяє ручний запуск

jobs:
  add_missing_dirs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Необхідно для запису змін (push) до репозиторію
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # fetch-depth: 0 # Зазвичай не потрібно для таких операцій, але не шкодить

      - name: Create Missing Directories and .gitkeep files
        id: create_dirs
        run: |
          directories_actually_created_or_updated=false # Прапорець, що вказує на фактичні зміни
          
          create_dir_and_gitkeep() {
            local dir_path="$1"
            if [ ! -d "$dir_path" ]; then
              mkdir -p "$dir_path"
              touch "$dir_path/.gitkeep"
              echo "Directory '$dir_path' and '$dir_path/.gitkeep' created."
              directories_actually_created_or_updated=true
            elif [ ! -f "$dir_path/.gitkeep" ]; then
              # Директорія існує, але .gitkeep відсутній
              touch "$dir_path/.gitkeep"
              echo "File '$dir_path/.gitkeep' created in existing directory."
              directories_actually_created_or_updated=true
            else
              echo "Directory '$dir_path' and '$dir_path/.gitkeep' already exist."
            fi
          }

          create_dir_and_gitkeep "shared"
          create_dir_and_gitkeep "infrastructure"
          create_dir_and_gitkeep "infrastructure/nginx"
          create_dir_and_gitkeep "infrastructure/ssl"
          
          echo "::set-output name=made_changes::$directories_actually_created_or_updated"
        shell: bash

      - name: Commit and Push Changes
        # Крок виконується, якщо прапорець made_changes встановлено в true
        if: steps.create_dirs.outputs.made_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Додаємо всі зміни. Оскільки ми створюємо .gitkeep, зміни будуть, якщо папки/файли були нові.
          git add .
          
          # Перевіряємо, чи є фактичні зміни, готові до коміту
          if ! git diff --staged --quiet; then
            echo "Changes detected by git, proceeding with commit and push."
            git commit -m "Chore: Ensure project directories (shared, infrastructure) and .gitkeep files exist"
            git push
            echo "Project directories and/or .gitkeep files ensured, committed, and pushed."
          else
            # Цей блок тепер менш імовірний, якщо made_changes == 'true', 
            # але залишаємо для повноти, якщо git add . чомусь не спрацює як очікувалось
            echo "Output 'made_changes' was true, but git detected no staged changes. This is unexpected."
            echo "Manual review of the workspace might be needed if directories were expected to be created/updated."
          fi
        shell: bash

      - name: No Changes Detected by Script
        # Крок виконується, якщо прапорець made_changes встановлено в false
        if: steps.create_dirs.outputs.made_changes == 'false'
        run: |
          echo "No missing directories or .gitkeep files were found/created by the script. No commit attempted."
        shell: bash
